server:
  port: 8181
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/dbTest?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password:

  redis:
    host: 127.0.0.1
    port: 60379
    database: 1
    password: Rqxyl2018

mybatis:
  type-aliases-package: com.ltnet.shopdemo.entity.*
  mapper-locations: classpath:mapper/*.xml

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: shopdemo-group

