server:
  port: 8088

spring:
  # database
  datasource:
    url: jdbc:mysql://localhost:3306/dbstock?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password:

    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  type-aliases-package: com.ltnet.elasticsearchdemo.entity.*
  mapper-locations: classpath:mapper/*.xml

elasticsearch:
  schema: http
  address: 192.168.210.200:9200
  connectTimeout: 5000
  socketTimeout: 50000
  connectionRequestTimeout: 5000
  maxConnectNum: 100
  maxConnectPerRoute: 100